import { CATEGORY_DICT, COMMON_STRINGS } from "./common.js";

const VALIDATION = {
  ...COMMON_STRINGS,
  RADIX_PARAM: 10,
  MIN_ITEM_QUANTITY_INCLUSIVE: 1,
  MIN_DATE_INCLUSIVE: 1,
  MAX_DATE_INCLUSIVE: 31,
  MAX_MENU_LENGTH_INLCUSLIVE: 20,
  NON_DRINK_CATEGORY: [
    CATEGORY_DICT.appetizer,
    CATEGORY_DICT.dessert,
    CATEGORY_DICT.main,
  ],
};

export default VALIDATION;
