import { DOMAIN } from "../../src/lib/Constants/index.js";

/**
 * @typedef {Object} MockedCase
 * @property {number} date
 * @property {[string]} rawOrders
 * @property {{appetizer: {}, main: {}, dessert:{}, drink: {}}} menus
 * @property {number} weekday
 * @property {number} weekend
 * @property {number} special
 * @property {number} christmas
 * @property {number} originalTotal
 * @property {boolean} eventFlag
 * @property {{}} reward
 * @property {{}} benefitInfo
 * @property {number} benefitValue
 * @property {number} discountedTotal
 * @property {string} badge
 * @property {[string]} logs
 */

/** @type {[MockedCase]} mockedCases */
const validCase = [
  {
    date: 3,
    rawOrders: [
      "샴페인-1",
      "시저샐러드-1",
      "바비큐립-1",
      "티본스테이크-2",
      "아이스크림-1",
      "양송이수프-1",
      "타파스-2",
      "해산물파스타-3",
      "크리스마스파스타-2",
      "제로콜라-1",
      "레드와인-2",
      "초코케이크-1",
    ],
    menus: {
      appetizer: { 시저샐러드: 1, 양송이수프: 1, 타파스: 2 },
      dessert: { 아이스크림: 1, 초코케이크: 1 },
      drink: { 레드와인: 2, 샴페인: 1, 제로콜라: 1 },
      main: {
        바비큐립: 1,
        크리스마스파스타: 2,
        티본스테이크: 2,
        해산물파스타: 3,
      },
    },
    weekday: 4046,
    weekend: 0,
    special: 1000,
    christmas: 1200,
    originalTotal: 512000,
    eventFlag: true,
    reward: { ...DOMAIN.REWARD_MENUS },
    benefitInfo: {
      weekday: 4046,
      weekend: 0,
      special: 1000,
      christmas: 1200,
      reward: 25000,
    },
    benefitValue: 31246,
    discountedTotal: 505754,
    badge: "산타",
    logs: [
      "12월 3일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!",
      "<주문 메뉴>",
      "샴페인 1개",
      "시저샐러드 1개",
      "바비큐립 1개",
      "티본스테이크 2개",
      "아이스크림 1개",
      "양송이수프 1개",
      "타파스 2개",
      "해산물파스타 3개",
      "크리스마스파스타 2개",
      "제로콜라 1개",
      "레드와인 2개",
      "초코케이크 1개",
      "<할인 전 총주문 금액>",
      "512,000원",
      "<증정 메뉴>",
      "샴페인 1개",
      "<혜택 내역>",
      "평일 할인: -4,046원",
      "특별 할인: -1,000원",
      "크리스마스 디데이 할인: -1,200원",
      "증정 이벤트: -25,000원",
      "<총혜택 금액>",
      "-31,246원",
      "<할인 후 예상 결제 금액>",
      "505,754원",
      "<12월 이벤트 배지>",
      "산타",
    ],
  },

  {
    date: 12,
    rawOrders: [
      "시저샐러드-1",
      "바비큐립-1",
      "해산물파스타-3",
      "크리스마스파스타-2",
      "제로콜라-1",
      "레드와인-2",
    ],
    menus: {
      appetizer: { 시저샐러드: 1 },
      dessert: {},
      drink: { 레드와인: 2, 제로콜라: 1 },
      main: { 바비큐립: 1, 크리스마스파스타: 2, 해산물파스타: 3 },
    },
    weekday: 0,
    weekend: 0,
    special: 0,
    christmas: 2100,
    originalTotal: 340000,
    eventFlag: true,
    reward: { ...DOMAIN.REWARD_MENUS },
    benefitInfo: {
      weekday: 0,
      weekend: 0,
      special: 0,
      christmas: 2100,
      reward: 25000,
    },
    benefitValue: 27100,
    discountedTotal: 337900,
    badge: "산타",
    logs: [
      "12월 12일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!",
      "<주문 메뉴>",
      "시저샐러드 1개",
      "바비큐립 1개",
      "해산물파스타 3개",
      "크리스마스파스타 2개",
      "제로콜라 1개",
      "레드와인 2개",
      "<할인 전 총주문 금액>",
      "340,000원",
      "<증정 메뉴>",
      "샴페인 1개",
      "<혜택 내역>",
      "크리스마스 디데이 할인: -2,100원",
      "증정 이벤트: -25,000원",
      "<총혜택 금액>",
      "-27,100원",
      "<할인 후 예상 결제 금액>",
      "337,900원",
      "<12월 이벤트 배지>",
      "산타",
    ],
  },

  {
    date: 26,
    rawOrders: ["초코케이크-1", "아이스크림-2", "제로콜라-1"],
    menus: {
      appetizer: {},
      dessert: { 아이스크림: 2, 초코케이크: 1 },
      drink: { 제로콜라: 1 },
      main: {},
    },
    weekday: 6069,
    weekend: 0,
    special: 0,
    christmas: 0,
    originalTotal: 28000,
    eventFlag: true,
    reward: {},
    benefitInfo: {
      weekday: 6069,
      weekend: 0,
      special: 0,
      christmas: 0,
      reward: 0,
    },
    benefitValue: 6069,
    discountedTotal: 21931,
    badge: "별",
    logs: [
      "12월 26일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!",
      "<주문 메뉴>",
      "초코케이크 1개",
      "아이스크림 2개",
      "제로콜라 1개",
      "<할인 전 총주문 금액>",
      "28,000원",
      "<증정 메뉴>",
      "없음",
      "<혜택 내역>",
      "평일 할인: -6,069원",
      "<총혜택 금액>",
      "-6,069원",
      "<할인 후 예상 결제 금액>",
      "21,931원",
      "<12월 이벤트 배지>",
      "별",
    ],
  },

  {
    date: 25,
    rawOrders: ["아이스크림-2"],
    menus: {
      appetizer: {},
      dessert: { 아이스크림: 2 },
      drink: {},
      main: {},
    },
    weekday: 4046,
    weekend: 0,
    special: 1000,
    christmas: 3400,
    originalTotal: 10000,
    eventFlag: true,
    reward: {},
    benefitInfo: {
      weekday: 4046,
      weekend: 0,
      special: 1000,
      christmas: 3400,
      reward: 0,
    },
    benefitValue: 8446,
    discountedTotal: 1554,
    badge: "별",
    logs: [
      "12월 25일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!",
      "<주문 메뉴>",
      "아이스크림 2개",
      "<할인 전 총주문 금액>",
      "10,000원",
      "<증정 메뉴>",
      "없음",
      "<혜택 내역>",
      "평일 할인: -4,046원",
      "특별 할인: -1,000원",
      "크리스마스 디데이 할인: -3,400원",
      "<총혜택 금액>",
      "-8,446원",
      "<할인 후 예상 결제 금액>",
      "1,554원",
      "<12월 이벤트 배지>",
      "별",
    ],
  },

  {
    date: 23,
    rawOrders: ["티본스테이크-1", "바비큐립-1", "타파스-2"],
    menus: {
      appetizer: { 타파스: 2 },
      dessert: {},
      drink: {},
      main: { 바비큐립: 1, 티본스테이크: 1 },
    },
    weekday: 0,
    weekend: 4046,
    special: 0,
    christmas: 3200,
    originalTotal: 120000,
    eventFlag: true,
    reward: { ...DOMAIN.REWARD_MENUS },
    benefitInfo: {
      weekday: 0,
      weekend: 4046,
      special: 0,
      christmas: 3200,
      reward: 25000,
    },
    benefitValue: 32246,
    discountedTotal: 112754,
    badge: "산타",
    logs: [
      "12월 23일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!",
      "<주문 메뉴>",
      "티본스테이크 1개",
      "바비큐립 1개",
      "타파스 2개",
      "<할인 전 총주문 금액>",
      "120,000원",
      "<증정 메뉴>",
      "샴페인 1개",
      "<혜택 내역>",
      "주말 할인: -4,046원",
      "크리스마스 디데이 할인: -3,200원",
      "증정 이벤트: -25,000원",
      "<총혜택 금액>",
      "-32,246원",
      "<할인 후 예상 결제 금액>",
      "112,754원",
      "<12월 이벤트 배지>",
      "산타",
    ],
  },

  {
    date: 8,
    rawOrders: [
      "양송이수프-1",
      "크리스마스파스타-2",
      "해산물파스타-1",
      "아이스크림-1",
      "제로콜라-1",
    ],
    menus: {
      appetizer: { 양송이수프: 1 },
      dessert: { 아이스크림: 1 },
      drink: { 제로콜라: 1 },
      main: { 크리스마스파스타: 2, 해산물파스타: 1 },
    },
    weekday: 0,
    weekend: 6069,
    special: 0,
    christmas: 1700,
    originalTotal: 99000,
    eventFlag: true,
    reward: {},
    benefitInfo: {
      weekday: 0,
      weekend: 6069,
      special: 0,
      christmas: 1700,
      reward: 0,
    },
    benefitValue: 7769,
    discountedTotal: 91231,
    badge: "별",
    logs: [
      "12월 8일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!",
      "<주문 메뉴>",
      "양송이수프 1개",
      "크리스마스파스타 2개",
      "해산물파스타 1개",
      "아이스크림 1개",
      "제로콜라 1개",
      "<할인 전 총주문 금액>",
      "99,000원",
      "<증정 메뉴>",
      "없음",
      "<혜택 내역>",
      "주말 할인: -6,069원",
      "크리스마스 디데이 할인: -1,700원",
      "<총혜택 금액>",
      "-7,769원",
      "<할인 후 예상 결제 금액>",
      "91,231원",
      "<12월 이벤트 배지>",
      "별",
    ],
  },

  {
    date: 7,
    rawOrders: ["양송이수프-1", "시저샐러드-1", "아이스크림-5"],
    menus: {
      appetizer: { 시저샐러드: 1, 양송이수프: 1 },
      dessert: { 아이스크림: 5 },
      drink: {},
      main: {},
    },
    weekday: 10115,
    weekend: 0,
    special: 0,
    christmas: 1600,
    originalTotal: 39000,
    eventFlag: true,
    reward: {},
    benefitInfo: {
      weekday: 10115,
      weekend: 0,
      special: 0,
      christmas: 1600,
      reward: 0,
    },
    benefitValue: 11715,
    discountedTotal: 27285,
    badge: "트리",
    logs: [
      "12월 7일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!",
      "<주문 메뉴>",
      "양송이수프 1개",
      "시저샐러드 1개",
      "아이스크림 5개",
      "<할인 전 총주문 금액>",
      "39,000원",
      "<증정 메뉴>",
      "없음",
      "<혜택 내역>",
      "평일 할인: -10,115원",
      "크리스마스 디데이 할인: -1,600원",
      "<총혜택 금액>",
      "-11,715원",
      "<할인 후 예상 결제 금액>",
      "27,285원",
      "<12월 이벤트 배지>",
      "트리",
    ],
  },

  {
    date: 31,
    rawOrders: ["샴페인-1", "크리스마스파스타-1"],
    menus: {
      appetizer: {},
      dessert: {},
      drink: { 샴페인: 1 },
      main: { 크리스마스파스타: 1 },
    },
    weekday: 0,
    weekend: 0,
    special: 1000,
    christmas: 0,
    originalTotal: 50000,
    eventFlag: true,
    reward: {},
    benefitInfo: {
      weekday: 0,
      weekend: 0,
      special: 1000,
      christmas: 0,
      reward: 0,
    },
    benefitValue: 1000,
    discountedTotal: 49000,
    badge: null,
    logs: [
      "12월 31일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!",
      "<주문 메뉴>",
      "샴페인 1개",
      "크리스마스파스타 1개",
      "<할인 전 총주문 금액>",
      "50,000원",
      "<증정 메뉴>",
      "없음",
      "<혜택 내역>",
      "특별 할인: -1,000원",
      "<총혜택 금액>",
      "-1,000원",
      "<할인 후 예상 결제 금액>",
      "49,000원",
      "<12월 이벤트 배지>",
      "없음",
    ],
  },

  {
    date: 24,
    rawOrders: ["타파스-1"],
    menus: {
      appetizer: { 타파스: 1 },
      dessert: {},
      drink: {},
      main: {},
    },
    weekday: 0,
    weekend: 0,
    special: 0,
    christmas: 0,
    originalTotal: 5500,
    eventFlag: false,
    reward: {},
    benefitInfo: {
      weekday: 0,
      weekend: 0,
      special: 0,
      christmas: 0,
      reward: 0,
    },
    benefitValue: 0,
    discountedTotal: 5500,
    badge: null,
    logs: [
      "12월 24일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!",
      "<주문 메뉴>",
      "타파스 1개",
      "<할인 전 총주문 금액>",
      "5,500원",
      "<증정 메뉴>",
      "없음",
      "<혜택 내역>",
      "없음",
      "<총혜택 금액>",
      "0원",
      "<할인 후 예상 결제 금액>",
      "5,500원",
      "<12월 이벤트 배지>",
      "없음",
    ],
  },
];

export default validCase;
